env:
  browser: true
  es2020: true
  node: true
extends:
- standard
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {}
overrides:
- files:
  - '**/*.test.js'
  plugins:
  - mocha
  extends:
  - plugin:mocha/recommended
  env:
    mocha: true
  rules:
    mocha/no-setup-in-describe:
    - off
    mocha/consistent-spacing-between-blocks:
    - off
